
conky.config = {
-- Size and Position settings --
  alignment = 'middle_middle',
  gap_x = -60,
  gap_y = 0,
  maximum_width = 900,
  minimum_height = 230,
  maximum_height = 300,
  minimum_width = 800,
 
-- Text settings --
  use_xft = true,
  override_utf8_locale = true,
  font = 'Roboto:size=9',
 
-- Color Settings --
  default_color = 'white',
  default_outline_color = 'white',
  default_shade_color = 'white',
  color1 = '#dadde3',
  color2 = '#8a95a8',
  color3 = '#d5dae3',
 
-- Window Settings --
  background = false,
  border_width = 1,
  draw_blended = false,
  draw_borders = false,
  draw_graph_borders = false,
  draw_outline = false,
  draw_shades = false,
  own_window = true,
  own_window_argb_value = 0,
  own_window_class = 'Conky',
  own_window_argb_visual = true,
  own_window_type = 'desktop',
  own_window_transparent = true,
  own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
  stippled_borders = 0,
 
-- Others --
  cpu_avg_samples = 2,
  net_avg_samples = 2,
  double_buffer = true,
  out_to_console = false,
  out_to_stderr = false,
  extra_newline = false,
  update_interval = 1,
  uppercase = false,
  use_spacer = 'none',
  show_graph_scale = false,
  show_graph_range = false,
}
 
conky.text = [[
${goto 100}${voffset 55}${font Rubik:Thin:size=70}${time %I:%M}${image line.png -p 354,23 -s 2x189}
${goto 275}${voffset -65}${font florentia:regular:size=25}${time %p}
${offset 385}${voffset -120}${font ADELE:size=30}${time %A,  %d %B}${font}
${offset 390}${voffset 15}${color3}${font JetBrains Mono:size=11}RAM:${memperc}%  CPU:${cpu cpu0}%  TEMP:${hwmon 0 temp 1}°C${font}
]]
