[/]
application-shortcuts=@aa{ss} []
category-icon-type='Full_Color'
default-menu-view-tognee='All_Programs'
directory-shortcuts=@aa{ss} []
enable-clock-widget-raven=false
enable-unity-homescreen=false
enable-weather-widget-raven=false
extra-categories=[(3, true), (2, true), (0, false), (1, false), (4, false)]
force-menu-location='Off'
group-apps-alphabetically-grid-layouts=false
group-apps-alphabetically-list-layouts=false
hide-overview-on-arcmenu-open=false
highlight-search-result-terms=true
menu-button-icon-size=22
menu-button-padding=-1
menu-button-text='Apps'
menu-item-icon-size='Extralarge'
menu-layout='raven'
menu-width-adjustment=-75
override-menu-theme=false
pinned-apps=@aa{ss} []
position-in-panel='Left'
power-display-style='In_Line'
power-options=[(7, false), (5, false), (6, false), (1, false), (2, false), (0, true), (4, true), (3, true)]
prefs-visible-page=0
raven-position='Right'
raven-search-display-style='Grid'
recently-installed-apps=['yelp.desktop', 'paprefs.desktop', 'qimgv.desktop']
scrollbars-overlay=false
scrollbars-visible=false
scrollview-fade-effect=true
search-entry-border-radius=(true, 5)
search-hidden=true
shortcut-icon-type='Symbolic'
show-activities-button=false
show-search-result-details=true
update-notifier-project-version=73
vert-separator=false
