[/]
auto-hide-search=true
clipboard-margin-right=55
clipboard-orientation='vertical'
clipboard-position-horizontal='bottom'
clipboard-position-vertical='fill'
clipboard-size=700
database-backend='json'
disable-hljs-dialog=false
dynamic-item-height=true
exclude-pinned=false
header-controls-visibility='visible-on-hover'
incognito=false
item-height=200
item-width=300
show-at-pointer=true
show-header=true

[file-item]
file-preview-visibility='file-info'

[link-item]
link-preview-orientation='horizontal'

[theme]
color-scheme='system'
theme='default'
