[/]
dnd-quick-toggle-enabled=false
media-compact=true
media-contorl-opacity=255
media-contorl-show-next-button=true
media-contorl-show-prev-button=true
media-enabled=true
media-gradient-enabled=false
media-progress-enabled=true
media-progress-handle-radius=2
media-progress-height=3
media-progress-style='slim'
media-remove-shadow=true
media-round-clip-enabled=true
media-round-clip-padding-adjustment-enabled=false
notifications-autohide=true
notifications-compact=true
notifications-enabled=true
notifications-fade-offset=0
notifications-remove-shadow=true
notifications-show-scrollbar=true
notifications-use-native-controls=true
system-indicator-layout-enabled=true
system-indicator-layout-order=[{'nonOrdered': <<true>>, 'hide': <<false>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'gtypeName': <<'Gjs_toggle_dndQuickToggle_DndIndicator'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'gtypeName': <<'Gjs_status_remoteAccess_RemoteAccessApplet'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'gtypeName': <<'Gjs_status_camera_Indicator'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'gtypeName': <<'Gjs_status_volume_InputIndicator'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'gtypeName': <<'Gjs_status_location_Indicator'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'gtypeName': <<'Gjs_status_thunderbolt_Indicator'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'gtypeName': <<'Gjs_status_nightLight_Indicator'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'gtypeName': <<'Gjs_status_network_Indicator'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'gtypeName': <<'Gjs_status_bluetooth_Indicator'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'gtypeName': <<'Gjs_status_rfkill_Indicator'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'gtypeName': <<'Gjs_status_volume_OutputIndicator'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'gtypeName': <<'Gjs_ui_panel_UnsafeModeIndicator'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'gtypeName': <<'Gjs_status_system_Indicator'>>}]
system-indicator-privacy-indicator-style='default'
system-indicator-screen-recording-indicator-use-accent=false
system-indicator-screen-sharing-indicator-use-accent=false
system-items-layout-enabled=false
system-items-layout-hide=false
system-items-layout-hide-settings=false
toggles-layout-enabled=true
toggles-layout-order=[{'hide': <<false>>, 'isSystem': <<true>>, 'constructorName': <<'NMWiredToggle'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'constructorName': <<'NMWirelessToggle'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'constructorName': <<'NMModemToggle'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'constructorName': <<'NMBluetoothToggle'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'constructorName': <<'NMVpnToggle'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'constructorName': <<'BluetoothToggle'>>}, {'hide': <<true>>, 'isSystem': <<true>>, 'constructorName': <<'PowerProfilesToggle'>>}, {'hide': <<true>>, 'isSystem': <<true>>, 'constructorName': <<'NightLightToggle'>>}, {'hide': <<true>>, 'isSystem': <<true>>, 'constructorName': <<'DarkModeToggle'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'constructorName': <<'KeyboardBrightnessToggle'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'constructorName': <<'RfkillToggle'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'constructorName': <<'RotationToggle'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'constructorName': <<'DndQuickToggle'>>}, {'hide': <<false>>, 'isSystem': <<true>>, 'constructorName': <<'UnsafeQuickToggle'>>}, {'nonOrdered': <<true>>, 'hide': <<false>>}]
unsafe-quick-toggle-enabled=false
volume-mixer-enabled=false
weather-compact=true
weather-enabled=false
weather-remove-shadow=true
